import type { Metadata } from 'next';
import { FaqAccordion } from '@/components/FaqAccordion';
import { JsonLd } from '@/components/JsonLd';

export const metadata: Metadata = {
  title: 'FAQ',
  description: 'How Cinderpass works, how strong the security is, and what happens to your secrets.',
};

const sections = [
  {
    heading: 'Using the app',
    items: [
      {
        q: 'What happens when someone opens my link?',
        a: 'The recipient\'s browser fetches the ciphertext from the server and decrypts it locally using the key fragment in the URL. The server then permanently marks the secret as opened and destroyed. After that point the link is dead — no further retrieval is possible.',
      },
      {
        q: 'Can I open the link myself to check it worked?',
        a: 'No. The first successful retrieval burns the secret. If you open your own link, the recipient will get an "already opened" error. Use the label field to annotate what the secret is so you don\'t need to verify it yourself.',
      },
      {
        q: 'What is the difference between Direct share and Inbound request?',
        a: 'Direct share is for when you already have the secret and want to send it. You encrypt it, generate a link, and send that link to the recipient. Inbound request is for when you need someone to send you a secret — you generate a request page, share that URL, and the other person submits the secret through it. You then receive a reveal link to open.',
      },
      {
        q: 'What does the passphrase do and when should I use it?',
        a: 'A passphrase adds a second encryption layer on top of the URL key. Even if the link is intercepted, the attacker cannot decrypt the secret without also knowing the passphrase. Use it when the communication channel you\'re using to send the link is not fully trusted — for example, email. Send the passphrase through a different channel, like a phone call or a separate messaging app.',
      },
      {
        q: 'What if the link expires before the recipient opens it?',
        a: 'The link becomes invalid and the secret is permanently inaccessible. You\'ll need to create a new one. Choose a longer TTL (up to 7 days) if the recipient may not open it immediately.',
      },
      {
        q: 'Can I cancel a secret after sending it?',
        a: 'Yes. When you create a secret, a Destroy button appears next to the share link. Clicking it immediately and permanently destroys the secret — the link becomes invalid before anyone can open it.',
      },
      {
        q: 'Is there a size limit for secrets?',
        a: 'Secrets are capped at 48 KB of plaintext. This is more than enough for any credential, API key, certificate, or recovery code. Cinderpass is not designed for transferring files.',
      },
    ],
  },
  {
    heading: 'Security',
    items: [
      {
        q: 'Does Cinderpass ever see my secret?',
        a: 'No. Encryption happens entirely in your browser before anything is sent to the server. The server only stores ciphertext — the encrypted output. Without the decryption key, which never leaves your browser, the ciphertext is unreadable.',
      },
      {
        q: 'Where is the decryption key stored?',
        a: 'The key fragment is placed in the URL after the # character (the "hash" or "fragment"). Browsers intentionally do not include the fragment in HTTP requests, so it is never transmitted to the Cinderpass server. It exists only in the share link itself.',
      },
      {
        q: 'What happens if someone intercepts the link in transit?',
        a: 'If the link is intercepted and opened before the intended recipient, the secret is burned on first open and the recipient will see an "already opened" error — alerting them that something went wrong. A passphrase provides an additional layer: even with the link, the attacker cannot decrypt without the passphrase.',
      },
      {
        q: 'How strong is the encryption?',
        a: 'Secrets are encrypted with AES-256-GCM using a 256-bit key generated by the browser\'s cryptographically secure random number generator. AES-256-GCM is an authenticated cipher — it detects any tampering with the ciphertext. This is the same algorithm used by TLS 1.3 and is considered secure against all known attacks including quantum computing threats in the near term.',
      },
      {
        q: 'What does the passphrase protect against specifically?',
        a: 'The passphrase is derived using PBKDF2 with SHA-256 and 120,000 iterations, producing a second key that is XOR-applied to the main key. The derived verifier is stored server-side so the passphrase can be checked without burning the secret. A wrong passphrase increments a per-secret attempt counter — after 5 failures the secret is permanently locked.',
      },
      {
        q: 'Can Cinderpass employees read my secrets?',
        a: 'Not passively — the decryption key is in the URL fragment, which browsers never include in HTTP requests, so it is never transmitted to the server. The server stores only ciphertext. However, because the server also serves the JavaScript that runs in your browser, the security model depends on that code being what is publicly published on GitHub. A malicious or compromised server could serve modified JavaScript that exfiltrates the key. This is why the source code is open and every deployed build is linked to a specific commit — so you can verify what is actually running.',
      },
      {
        q: 'What if two people open the link at the same time?',
        a: 'Only one request can succeed. The burn step is an atomic database write that filters on status = ACTIVE. Whichever request commits first wins; the second sees count = 0 and gets an "already opened" error. The ciphertext is only returned inside the same transaction that marks the secret as destroyed.',
      },
      {
        q: 'Has Cinderpass been independently audited?',
        a: 'Not yet. An independent security review is on the roadmap. In the meantime, the full source code is publicly available and the deployed build is linked to a specific commit so anyone can verify the code running in production matches what is in the repository.',
      },
    ],
  },
  {
    heading: 'Trust & verification',
    items: [
      {
        q: 'How do I know the deployed app matches the open-source code?',
        a: 'The footer of every page shows a short commit hash that links directly to the corresponding commit on GitHub. The GET /api/version endpoint returns the full commit SHA and build timestamp in JSON. You can compare these against the public repository to verify the deployed code.',
      },
      {
        q: 'Can I self-host Cinderpass?',
        a: 'Yes. Cinderpass is a standard Next.js application backed by PostgreSQL. Clone the repository, set the three environment variables in .env.example, run the Prisma migrations, and deploy anywhere that runs Node.js. Vercel with a Postgres add-on is the fastest path.',
      },
      {
        q: 'Is the source code open?',
        a: 'Yes. The full source is available at github.com/eleco/cinderpass under the MIT licence. You are free to inspect, fork, self-host, or contribute.',
      },
    ],
  },
  {
    heading: 'Data & privacy',
    items: [
      {
        q: 'What data does Cinderpass store?',
        a: 'For each secret: the ciphertext, IV, algorithm identifier, a label (if provided), expiry timestamp, creation timestamp, status, and — when a passphrase is used — a derived verifier and salt. The server never stores plaintext, the decryption key, or the passphrase itself.',
      },
      {
        q: 'How long is data retained?',
        a: 'Secrets are stored until their TTL expires (maximum 7 days) or until they are opened or destroyed. An hourly background job marks expired records. Opened and destroyed records remain in the database as audit rows but the ciphertext is inaccessible by design — the key needed to decrypt it was never stored.',
      },
      {
        q: 'Is any personal information collected?',
        a: 'No accounts, no email addresses, no tracking. IP addresses may appear in server access logs at the infrastructure level (Vercel, Neon) for standard operational purposes, but Cinderpass itself does not store or log IP addresses.',
      },
    ],
  },
];

const base = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  url: `${base}/faq`,
  mainEntity: sections.flatMap((s) =>
    s.items.map((item) => ({
      '@type': 'Question',
      name: item.q,
      acceptedAnswer: { '@type': 'Answer', text: item.a },
    }))
  ),
};

export default function FaqPage() {
  return (
    <main className="dest-shell">
      <JsonLd data={faqSchema} />
      <div className="dest-container" style={{ maxWidth: 780 }}>
        <div className="dest-brand">
          <a href="/" className="badge badge-solid">Cinderpass</a>
        </div>
        <div style={{ display: 'grid', gap: '0.5rem' }}>
          <h1 style={{ margin: 0, fontFamily: 'var(--font-display)', letterSpacing: '-0.04em', fontSize: 'clamp(2rem, 5vw, 3rem)', lineHeight: 1 }}>
            Frequently asked questions
          </h1>
          <p className="muted" style={{ margin: 0, fontSize: '1.05rem' }}>
            How Cinderpass works, how strong the security is, and what happens to your secrets.
          </p>
        </div>
        <FaqAccordion sections={sections} />
      </div>
    </main>
  );
}
